#ifndef CERTIFICADO_H
#define CERTIFICADO_H

const char CERTIFICATE[] =
"-----BEGIN CERTIFICATE-----\n"
"MIIDojCCA0egAwIBAgIRALSDp+zGlOp5Eyk3ideWifowCgYIKoZIzj0EAwIwOzEL\n"
"MAkGA1UEBhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczEMMAoG\n"
"A1UEAxMDV0UxMB4XDTI1MDQwMjAwMDI0MFoXDTI1MDcwMTAxMDIzNVowFDESMBAG\n"
"A1UEAxMJcmVxcmVzLmluMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAX/h8KM9\n"
"XF232MyGkR22AaKhZWx2FxxevNAIwj2kLhFXL93p4i85cHAvEhxGECBXBc9EXwIz\n"
"uQlOZW5UL1i906OCAlEwggJNMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggr\n"
"BgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRXvfTYllBM8T16NSG2bML3\n"
"VoI0sjAfBgNVHSMEGDAWgBSQd5I1Z8T/qMyp5nvZgHl7zJP5ODBeBggrBgEFBQcB\n"
"AQRSMFAwJwYIKwYBBQUHMAGGG2h0dHA6Ly9vLnBraS5nb29nL3Mvd2UxL3RJTTAl\n"
"BggrBgEFBQcwAoYZaHR0cDovL2kucGtpLmdvb2cvd2UxLmNydDAhBgNVHREEGjAY\n"
"gglyZXFyZXMuaW6CCyoucmVxcmVzLmluMBMGA1UdIAQMMAowCAYGZ4EMAQIBMDYG\n"
"A1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jLnBraS5nb29nL3dlMS9KVHdQZGNoX2VD\n"
"OC5jcmwwggEGBgorBgEEAdZ5AgQCBIH3BIH0APIAdwDd3Mo0ldfhFgXnlTL6x5/4\n"
"PRxQ39sAOhQSdgosrLvIKgAAAZX0BZK6AAAEAwBIMEYCIQDEC8bYC5J4Nf4Ryhg/\n"
"y0ir1hmDh8AXjmD0BlWE8VaMhAIhAKEf7tamRFQon6hWnvNC4ZT+6q42KCySwWpB\n"
"Y7FQjqi1AHcADeHyMCvTDcFAYhIJ6lUu/Ed0fLHX6TDvDkIetH5OqjQAAAGV9AWW\n"
"fgAABAMASDBGAiEA/omFqCW2CduXZKZRSnu7q4vzV9ClzKKg3mS7okgIWrwCIQDV\n"
"FJHw+Rcy2AjE9Kg7M455lzksuonVakm2++sUJ10C6TAKBggqhkjOPQQDAgNJADBG\n"
"AiEAifPVggviPJk1n/MmWGCiw/WxH95G/haO26krjOznV3MCIQDeyWlM7zjLlE3Y\n"
"MCo7sx4wtoAhttwclT7rs2/854bOWg==\n"
"-----END CERTIFICATE-----\n";

#endif // CERTIFICADO_H



